# action.yml
name: 'Compose Compiler Metrics'
description: 'Print compose compiler metrics'
inputs:
  directory:
    description: 'compose-metrics report directory name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
branding:
  icon: 'file-text'
  color: 'red'